In [1]:
# !pip install nltk

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('E:\Python\ML\Ecommerce_data.csv')
df.head(5)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\Dell\AppData\Local\Temp\ipykernel_16640\2929440702.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv('E:\Python\ML\Ecommerce_data.csv')


Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

# Convert to lower case
# Remove stopping words and punctuation

In [4]:
sentences=[
    'python is a great programming language',
    'I love learning programming in python',
    'data science and python programming are related'
]

In [5]:
df['label'].value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [6]:
label ={'Household' :0 , 'Electronics':1, 'Clothing & Accessories':2, 'Books':3}
df['label_encode']=df['label'].map(label)
df.head(5)

Text                   label  \
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household   
1  Contrast living Wooden Decorative Box,Painted ...               Household   
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics   
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories   
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories   

   label_encode  
0             0  
1             0  
2             1  
3             2  
4             2

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
tfdif_matrix= vectorizer.fit_transform(sentences)
tfidf_array=tfdif_matrix.toarray()
tfidf_array
# 3 sentences X 13 unique keywords matrix
# Each word becomes feature columns
#X = vectorizer.fit_transform(df['Text'])
#y = df['label_encode']
# Term Frequency , Inverse document Frequency

array([[0.        , 0.        , 0.        , 0.52004008, 0.        ,
        0.52004008, 0.52004008, 0.        , 0.        , 0.30714405,
        0.30714405, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.52004008,
        0.        , 0.        , 0.52004008, 0.52004008, 0.30714405,
        0.30714405, 0.        , 0.        ],
       [0.4189401 , 0.4189401 , 0.4189401 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.24743277,
        0.24743277, 0.4189401 , 0.4189401 ]])

In [8]:
features=vectorizer.get_feature_names_out()

In [9]:
for i, sentences in enumerate(sentences):
  print(f'{i+1} : {sentences}')
  print('TF-IDF scores')
  for word, score in zip(features, tfidf_array[i]):
    print(f'{word} : {score}')
  print()

1 : python is a great programming language
TF-IDF scores
and : 0.0
are : 0.0
data : 0.0
great : 0.5200400832078022
in : 0.0
is : 0.5200400832078022
language : 0.5200400832078022
learning : 0.0
love : 0.0
programming : 0.3071440505460478
python : 0.3071440505460478
related : 0.0
science : 0.0

2 : I love learning programming in python
TF-IDF scores
and : 0.0
are : 0.0
data : 0.0
great : 0.0
in : 0.5200400832078022
is : 0.0
language : 0.0
learning : 0.5200400832078022
love : 0.5200400832078022
programming : 0.3071440505460478
python : 0.3071440505460478
related : 0.0
science : 0.0

3 : data science and python programming are related
TF-IDF scores
and : 0.4189401020758947
are : 0.4189401020758947
data : 0.4189401020758947
great : 0.0
in : 0.0
is : 0.0
language : 0.0
learning : 0.0
love : 0.0
programming : 0.24743277305481848
python : 0.24743277305481848
related : 0.4189401020758947
science : 0.4189401020758947



In [10]:
import string
df['Text']=df['Text'].map(lambda sentence: sentence.lower().translate(str.maketrans('', '', string.punctuation)))
df.head(5)

Text                   label  \
0  urban ladder eisner low back studyoffice compu...               Household   
1  contrast living wooden decorative boxpainted b...               Household   
2  io crest sypci40010 pci raid host controller c...             Electronics   
3  isakaa baby socks from just born to 8 years pa...  Clothing & Accessories   
4  indira designer womens art mysore silk saree w...  Clothing & Accessories   

   label_encode  
0             0  
1             0  
2             1  
3             2  
4             2

In [11]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
stop_words=nltk.corpus.stopwords.words('english')


In [13]:
#[ var for var in iterable if condition: statement]
def prepocessing(sentence):
  words=sentence.split()
  filtered_tokens=[word for word in words if word not in stop_words]
  return ' '.join(filtered_tokens)

In [14]:
df['Filtered_tokens']=df['Text'].map(prepocessing)
df.head(5)

Text                   label  \
0  urban ladder eisner low back studyoffice compu...               Household   
1  contrast living wooden decorative boxpainted b...               Household   
2  io crest sypci40010 pci raid host controller c...             Electronics   
3  isakaa baby socks from just born to 8 years pa...  Clothing & Accessories   
4  indira designer womens art mysore silk saree w...  Clothing & Accessories   

   label_encode                                    Filtered_tokens  
0             0  urban ladder eisner low back studyoffice compu...  
1             0  contrast living wooden decorative boxpainted b...  
2             1  io crest sypci40010 pci raid host controller c...  
3             2  isakaa baby socks born 8 years pack 4 6 8 12 i...  
4             2  indira designer womens art mysore silk saree b...

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
# vectorizer = TfidfVectorizer()
# tfdif_matrix= vectorizer.fit_transform(df['Filtered_tokens'])
# tfidf_array=tfdif_matrix.toarray()
# # tfidf_array

In [16]:
from sklearn.model_selection import train_test_split
X = df['Filtered_tokens']
Y= df['label_encode']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix
vectorizer = TfidfVectorizer()
X_train_pre = vectorizer.fit_transform(X_train)
X_test_pre = vectorizer.transform(X_test)
clf = MultinomialNB()
clf.fit(X_train_pre,Y_train)
y_pred = clf.predict(X_test_pre)
print(accuracy_score(Y_test,y_pred))
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

0.9635416666666666
[[1154   16   14   10]
 [  20 1200    1    8]
 [   8    7 1171    4]
 [  50   22   15 1100]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      1194
           1       0.96      0.98      0.97      1229
           2       0.98      0.98      0.98      1190
           3       0.98      0.93      0.95      1187

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800



In [18]:
a = np.array([[0.8,0.44],[-1.28,-1.43],[0.49,0.99]])
b = np.array([[0.707,-0.707],[0.707,0.707]])
zp = np.dot(a,b)
zp

array([[ 0.87668, -0.25452],
       [-1.91597, -0.10605],
       [ 1.04636,  0.3535 ]])